mapnik:
  # transportation: roads.mss
  - { min_zoom:  6, name: motorway, width: 52, height: 5, fill: "#e892a2", stroke: "#dc2a67", geometry: "=" }
  - { min_zoom:  6, name: main_road, image: mainroad.png }
  - { min_zoom:  8, name: main_road, image: mainroad8.png }
  - { min_zoom: 12, name: main_road, image: mainroad12.png }
  - { min_zoom: 13, name: track, width: 52, height: 3, opacity: .8, stroke: "#996600", stroke-width: 1.5, stroke-dasharray: "6 5", geometry: "-" }
  - { min_zoom: 13, name: bridleway, width: 52, height: 3, stroke: green, stroke-width: 1.25, stroke-dasharray: "4 2", geometry: "-" }
  - { min_zoom: 13, name: cycleway, width: 52, height: 1, stroke: blue, stroke-dasharray: "3 3.5", geometry: "-" }
  - { min_zoom: 13, name: footway, width: 52, height: 3, stroke: salmon, stroke-width: 1.3, stroke-dasharray: "3 3.5", geometry: "-" }
  - { min_zoom:  8, name: rail, width: 52, height: 1, fill: "#787878" }
  - { min_zoom: 12, name: rail, width: 52, height: 3, fill: "#707070", stroke: white, stroke-dasharray: 8, stroke-dashoffset: 2, geometry: "-" }
  - { min_zoom: 18, name: rail, width: 52, height: 4, fill: "#707070", stroke: white, stroke-dasharray: 8, stroke-dashoffset: 2, stroke-width: 2, geometry: "-" }
  - { min_zoom: 12, name: subway, width: 52, height: 2, fill: "#999" }
  - { min_zoom:  8, name: light_rail, width: 52, height: 1, fill: "#ccc" }
  - { min_zoom: 10, name: light_rail, width: 52, height: 1, fill: "#aaa" }
  - { min_zoom: 13, name: light_rail, width: 52, height: 2, fill: "#666" }
  - { min_zoom: 12, name: tram_only, width: 52, height: 1, geometry: "-", stroke: "#6e6e6e", stroke-width: 0.75 }
  - { min_zoom: 14, name: tram_only, width: 52, height: 3, geometry: "-", stroke: "#6e6e6e", stroke-width: 1 }
  - { min_zoom: 15, name: tram_only, width: 52, height: 3, geometry: "-", stroke: "#6e6e6e", stroke-width: 1.5 }
  - { min_zoom: 17, name: tram_only, width: 52, height: 2, geometry: "-", stroke: "#6e6e6e", stroke-width: 2 }
  - { min_zoom: 12, name: [cable_car, chair_lift], image: cable.png }
  - { min_zoom: 11, name: [runway_only, taxiway], image: runway11.svg }
  - { min_zoom: 12, name: [runway_only, taxiway], image: runway12.svg }
  - { min_zoom: 13, name: [runway_only, taxiway], image: runway13.svg }
  - { min_zoom: 14, name: [runway_only, taxiway], image: runway14.svg }
  - { min_zoom: 11, name: apron_only, width: 26, height: 10, fill: "#dadae0" } # landcover.mss
  # administrative boundaries: admin.mss
  - { name: admin, width: 52, height: 2, fill: "#8d618b88" }
  # landcover z5: landcover.mss, water.mss
  - { name: [lake_only, reservoir], width: 26, height: 10, fill: "#aad3df" }
  - { name: intermittent_water, image: intermittent_water.svg }
  - { min_zoom:  5, name: glacier, width: 26, height: 10, fill: "#ddecec", stroke: "#9cf" }
  - { min_zoom: 10, name: glacier, width: 26, height: 10, fill: "#ddecec", stroke: "#9cf", stroke-dasharray: "4 2" }
  - { min_zoom: 10, name: reef, image: reef.png }
  - { min_zoom: 10, name: wetland, image: wetland.png }
  - { min_zoom:  5, name: [forest_only, wood], width: 26, height: 10, fill: "#bddab1" }
  - { min_zoom: 12, name: [forest_only, wood], width: 26, height: 10, fill: "#add19e" }
  - { min_zoom:  5, name: [orchard_only, vineyard], width: 26, height: 10, fill: "#bee5b5" }
  - { min_zoom: 12, name: [orchard_only, vineyard], width: 26, height: 10, fill: "#aedfa3" }
  - { min_zoom:  5, name: [grass_only, meadow], width: 26, height: 10, fill: "#d7efc0" }
  - { min_zoom: 12, name: [grass_only, meadow], width: 26, height: 10, fill: "#cdebb0" }
  - { min_zoom:  5, name: farmland, width: 26, height: 10, fill: "#f1f3dd" }
  - { min_zoom: 12, name: farmland, width: 26, height: 10, fill: "#eef0d5" }
  - { min_zoom:  5, name: heathland, width: 26, height: 10, fill: "#dee1b2" }
  - { min_zoom: 12, name: heathland, width: 26, height: 10, fill: "#d6d99f" }
  - { min_zoom:  5, name: scrubland, width: 26, height: 10, fill: "#d3dfbc" }
  - { min_zoom: 12, name: scrubland, width: 26, height: 10, fill: "#c8d7ab" }
  - { min_zoom:  5, name: bare_rock, width: 26, height: 10, fill: "#f1eae3" }
  - { min_zoom: 12, name: bare_rock, width: 26, height: 10, fill: "#eee5dc" }
  - { min_zoom:  5, name: sand, width: 26, height: 10, fill: "#f7edd1" }
  - { min_zoom: 12, name: sand, width: 26, height: 10, fill: "#f5e9c6" }
  # landuse z8, z10: landcover.mss
  - { min_zoom: 10, name: park, width: 26, height: 10, fill: "#c8facc" }
  - { min_zoom: 10, name: golf, width: 26, height: 10, fill: "#def6c0" }
  - { min_zoom:  8, name: built_up, width: 26, height: 10, fill: "#d9d9d9" }
  - { min_zoom: 12, max_zoom: 12, name: built_up, width: 26, height: 10, fill: "#dddddd" }
  - { min_zoom: 13, name: resident, width: 26, height: 10, fill: "#e0dfdf" }
  - { min_zoom: 13, name: retail, width: 26, height: 10, fill: "#ffd6d1" }
  - { min_zoom: 13, name: commercial, width: 26, height: 10, fill: "#f2dad9" }
  - { min_zoom: 13, name: industrial, width: 26, height: 10, fill: "#ebdbe8" }
  - { min_zoom: 10, name: farm, width: 26, height: 10, fill: "#f7e3c8" }
  - { min_zoom: 12, name: farm, width: 26, height: 10, fill: "#f5dcba" }
  - { min_zoom: 10, name: brownfield, width: 26, height: 10, fill: "#d2d2c3" }
  - { min_zoom: 12, name: brownfield, width: 26, height: 10, fill: "#c7c7b4" }
  - { min_zoom: 10, name: cemetery, width: 26, height: 10, fill: "#bbd5be" }
  - { min_zoom: 12, name: cemetery, width: 26, height: 10, fill: "#aacbaf" }
  - { min_zoom: 10, name: allotments, width: 26, height: 10, fill: "#d4e6cc" }
  - { min_zoom: 12, name: allotments, width: 26, height: 10, fill: "#c9e1bf" }
  - { min_zoom: 11, name: pitch, width: 26, height: 10, fill: "#88e0be" }
  - { min_zoom: 11, name: centre, width: 26, height: 10, fill: "#dffce2" }
  - { min_zoom: 10, name: reserve, image: reserve.svg } # admin.mss
  - { min_zoom:  8, name: military, image: military.svg }
  - { min_zoom: 13, name: [school_only, university, hospital], image: school.svg }
  # buildings: buildings.mss
  - { min_zoom: 14, name: building, width: 10, height: 10, fill: "#ab9793" }
  - { min_zoom: 15, name: building, width: 10, height: 10, fill: "#b9a99c", stroke: "#a99a8d" }
  - { min_zoom: 16, name: building, width: 10, height: 10, fill: "#c4b6ab", stroke: "#a99a8d" }
  # stations: stations.mss
  - { min_zoom: 12, name: station, width: 4, height: 4, fill: "#7981b0" }
  - { min_zoom: 13, name: station, width: 6, height: 6, fill: "#7981b0" }
  - { min_zoom: 15, name: station, width: 9, height: 9, fill: "#7981b0" }
  # other
  - { min_zoom: 11, name: [summit_only, peak], image: summit.svg } # amenity-points.mss
  - { min_zoom: 13, name: tunnel, width: 50, height: 5, stroke: grey, stroke-dasharray: "4 2", stroke-dashoffset: 1, geometry: "=" } # roads.mss
  - { min_zoom: 13, name: bridge, width: 50, height: 5, stroke: black, geometry: "=" } # roads.mss
  - { min_zoom: 15, name: private, image: private.png }
  - { min_zoom: 15, name: destination, image: destination.png }
  - { min_zoom: 12, name: construction, image: construction.png }
cyclemap:
  - { min_zoom:  5, name: motorway, width: 50, height: 3, fill: "#9a9ab1" }
  - { min_zoom: 12, name: motorway, width: 50, height: 5, fill: "#bdbece", stroke: "#8d95a7", geometry: "=" }
  - { min_zoom:  6, name: trunk, width: 50, height: 2, fill: "#c8d8c8" }
  - { min_zoom: 12, name: trunk, width: 50, height: 5, fill: "#c8d8c8", stroke: "#abb5a4", geometry: "=" }
  - { min_zoom:  8, name: primary, width: 50, height: 2, fill: "#d8c8c8" }
  - { min_zoom: 12, name: primary, width: 50, height: 4, fill: "#f0e3e3", stroke: "#d4b6b7", geometry: "=" }
  - { min_zoom: 10, name: secondary, width: 50, height: 1, fill: "#dadacc" }
  - { min_zoom: 12, name: secondary, width: 50, height: 4, fill: "#ededc8", stroke: "#c8b48a", geometry: "=" }
  - { min_zoom: 15, name: pedestrian, width: 50, height: 4, fill: "#e2e3e2", stroke: "#9a9a9a", geometry: "=" }
  - { min_zoom: 13, name: track, width: 50, height: 3, fill: white, stroke: "#999", stroke-dasharray: "5 3", stroke-dashoffset: 1, geometry: "=" }
  - { min_zoom: 15, name: track, width: 50, height: 4, fill: white, stroke: "#999", stroke-dasharray: "5 3", stroke-dashoffset: 1, geometry: "=" }
  - { min_zoom: 17, name: track, width: 50, height: 5, fill: white, stroke: "#999", stroke-dasharray: "5 3", stroke-dashoffset: 1, geometry: "=" }
  - { min_zoom:  8, name: cycleway, width: 50, height: 3, stroke: "#0100fe", stroke-width: 1.5, stroke-dasharray: "6 2", geometry: "-" }
  - { min_zoom:  5, name: cycleway_national, width: 50, height: 2, fill: "#fe0000" }
  - { min_zoom: 13, name: cycleway_national, width: 50, height: 4, fill: "#ffb3b3" }
  - { min_zoom:  7, name: cycleway_regional, width: 50, height: 2, fill: "#b638fb" }
  - { min_zoom: 13, name: cycleway_regional, width: 50, height: 4, fill: "#ddb5d9" }
  - { min_zoom:  8, name: cycleway_local, width: 50, height: 2, fill: "#0100fe" }
  - { min_zoom: 13, name: cycleway_local, width: 50, height: 4, fill: "#b2b2ff" }
  - { min_zoom: 13, name: footway, width: 50, height: 3, stroke: "#bd6d6e", stroke-width: 1.5, stroke-dasharray: "6 2", geometry: "-" }
  - { min_zoom:  7, name: rail, width: 50, height: 3, stroke: "#999999", stroke-width: 1.5, geometry: "-" }
  - { min_zoom: 14, name: rail, width: 50, height: 4, fill: "#999999", stroke: white, stroke-dasharray: 4, stroke-width: 2, geometry: "-" }
  - { min_zoom:  1, name: [lake_only, reservoir], width: 26, height: 10, fill: "#addeff" }
  - { min_zoom:  9, name: [forest_only, wood], width: 26, height: 10, fill: "#b3d6a4" }
  - { min_zoom: 10, name: meadow, width: 26, height: 10, fill: "#c0de9c" }
  - { min_zoom: 10, name: park, width: 26, height: 10, fill: "#cbe4c4" }
  - { min_zoom: 10, name: common_only, width: 26, height: 10, fill: "#d4f0d1" }
  - { min_zoom: 14, name: bicycle_shop, image: bicycle_shop.png }
  - { min_zoom: 14, name: bicycle_parking, image: bicycle_parking.png }
  - { min_zoom: 16, name: toilets, image: toilets.png }
opnvkarte:
  - { min_zoom:  6, name: rail, width: 52, height: 1, fill: "#868686" }
  - { min_zoom:  8, name: rail, width: 52, height: 2, fill: "#868686" }
  - { min_zoom: 11, name: rail, width: 52, height: 3, fill: "#868686", stroke: "#eeeeee", stroke-dasharray: 10, stroke-dashoffset: 9, geometry: "-" }
  - { min_zoom: 15, name: rail, width: 52, height: 4, fill: "#868686", stroke: "#eeeeee", stroke-dasharray: 10, stroke-dashoffset: 9, stroke-width: 2, geometry: "-" }
  - { min_zoom: 17, name: rail, image: rail17.svg }
  - { min_zoom:  6, name: train, width: 52, height:  2, fill: "#ffc366" }
  - { min_zoom: 10, name: train, width: 52, height:  3, fill: "#ffc366" }
  - { min_zoom: 12, name: train, width: 52, height:  4, fill: "#ffc366" }
  - { min_zoom: 14, name: train, width: 52, height:  8, fill: "#ffc366" }
  - { min_zoom: 16, name: train, width: 52, height: 10, fill: "#ffc366" }
  - { min_zoom: 10, name: light_rail, width: 52, height:  3, fill: "#66ff66" }
  - { min_zoom: 12, name: light_rail, width: 52, height:  4, fill: "#66ff66" }
  - { min_zoom: 14, name: light_rail, width: 52, height:  8, fill: "#66ff66" }
  - { min_zoom: 16, name: light_rail, width: 52, height: 10, fill: "#66ff66" }
  - { min_zoom: 10, name: tram_only, width: 52, height:  3, fill: "#3333fe" }
  - { min_zoom: 12, name: tram_only, width: 52, height:  4, fill: "#3333fe" }
  - { min_zoom: 14, name: tram_only, width: 52, height:  8, fill: "#3333fe" }
  - { min_zoom: 16, name: tram_only, width: 52, height: 10, fill: "#3333fe" }
  - { min_zoom: 10, name: subway, width: 52, height:  3, fill: "#33339f" }
  - { min_zoom: 12, name: subway, width: 52, height:  4, fill: "#33339f" }
  - { min_zoom: 14, name: subway, width: 52, height:  8, fill: "#33339f" }
  - { min_zoom: 16, name: subway, width: 52, height: 10, fill: "#33339f" }
  - { min_zoom:  9, name: ferry, width: 52, height: 2, fill: "#9f339f" }
  - { min_zoom: 14, name: ferry, width: 52, height: 3, fill: "#9f339f" }
  - { min_zoom: 10, name: trolleybus, width: 52, height:  3, fill: "#9f3333" }
  - { min_zoom: 12, name: trolleybus, width: 52, height:  4, fill: "#9f3333" }
  - { min_zoom: 14, name: trolleybus, width: 52, height:  8, fill: "#9f3333" }
  - { min_zoom: 16, name: trolleybus, width: 52, height: 10, fill: "#9f3333" }
  - { min_zoom: 11, name: bus, width: 52, height:  1, fill: "#fe3333" }
  - { min_zoom: 12, name: bus, width: 52, height:  2, fill: "#fe3333" }
  - { min_zoom: 13, name: bus, width: 52, height:  3, fill: "#fe3333" }
  - { min_zoom: 14, name: bus, width: 52, height:  4, fill: "#fe3333" }
  - { min_zoom: 16, name: bus, width: 52, height: 10, fill: "#fe3333" }
  - { min_zoom: 13, name: bus_stop, image: bus_stop13.svg }
  - { min_zoom: 15, name: bus_stop, image: bus_stop15.svg }
  - { min_zoom: 13, name: stop, image: stop13.svg }
  - { min_zoom: 15, name: stop, image: stop15.svg }
  - { min_zoom:  8, name: motorway, width: 52, height: 4, fill: "#dddddd", stroke: "#6d6d6d", geometry: "=" }
  - { min_zoom: 13, name: motorway, width: 52, height: 8, fill: "#dddddd", stroke: "#6d6d6d", geometry: "=" }
  - { min_zoom: 15, name: motorway, image: motorway15.svg }
  - { min_zoom: 17, name: motorway, image: motorway17.svg }
  - { min_zoom:  8, name: main_road, width: 52, height:  1, fill: "#5c6d6d88" }
  - { min_zoom: 11, name: main_road, width: 52, height:  4, fill: "#dddddd", stroke: "#a1968b", geometry: "=" }
  - { min_zoom: 13, name: main_road, width: 52, height:  8, fill: "#dddddd", stroke: "#a1968b", geometry: "=" }
  - { min_zoom: 15, name: main_road, width: 52, height: 13, fill: "#dddddd", stroke: "#a1968b", geometry: "=" }
  - { min_zoom: 17, name: main_road, width: 52, height: 17, fill: "#dddddd", stroke: "#a1968b", geometry: "=" }
  # landcover
  - { min_zoom:  0, name: [lake_only, reservoir], width: 26, height: 10, fill: "#a1cbea" }
  - { min_zoom:  8, name: [lake_only, reservoir], width: 26, height: 10, fill: "#bfd3ef" }
  - { min_zoom:  4, name: [forest_only, wood], width: 26, height: 10, fill: "#b9c5a3" }
  - { min_zoom:  4, name: built_up, width: 26, height: 10, fill: "#d8d8d8" }
  - { min_zoom:  9, name: farmland, width: 26, height: 10, fill: "#eae8d6" }
  - { min_zoom: 12, name: [park, allotments], width: 26, height: 10, fill: "#c2d89a" }
